### ISSUE TITLE
DFT of arbitrary size of input signal

### ISSUE THREAD

**Issue by Marcuslief** [HiFi-LoFi/AudioFFT#1]
I had a question...while calculating fft of input samples, does this code takes arbitrary size of input and calculate say 4096-fft, because apparently it calculates only if the no. of input samples is same as the fftsize? Please help..

**Comment by HiFi-LoFi** [comment]
Hi Marcuslief,

no, this library always expects the same number of samples passed to init(), which must be a power of 2, i.e. it is not possible to call fft() or ifft() with a varying number of samples (due to pre-allocated buffers and prepared FFT plans in init() which refer to the same size).

I'm not aware of any fast FFT implementation which supports this. However, if you need non-power-of-2 FFT sizes, then the KissFFT might work for you (but it is slower).

In many cases, it works pretty well to apply padding to your buffer if it is smaller then the initialized number of samples (I do this in FFTConvolver, for example).

Hope this helps!

Regards, Uli
